/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/common/AppFooter.vue')['default']
    AppHeader: typeof import('./components/common/AppHeader.vue')['default']
    AppSidebar: typeof import('./components/common/AppSidebar.vue')['default']
    AutoMATATraining: typeof import('./components/AutoMATATraining.vue')['default']
    AutoMATATrainingSemi: typeof import('./components/AutoMATATrainingSemi.vue')['default']
    AutoMATATrainingSimple: typeof import('./components/AutoMATATrainingSimple.vue')['default']
    AutoMATATrainingSupervised: typeof import('./components/AutoMATATrainingSupervised.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElNotification: typeof import('element-plus/es')['ElNotification']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ErrorBoundary: typeof import('./components/common/ErrorBoundary.vue')['default']
    FileChunkedDownloader: typeof import('./components/FileChunkedDownloader.vue')['default']
    FileUploader: typeof import('./components/FileUpload/FileUploader.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    JobList: typeof import('./components/Job/JobList.vue')['default']
    JobStatus: typeof import('./components/Job/JobStatus.vue')['default']
    LoadingSpinner: typeof import('./components/common/LoadingSpinner.vue')['default']
    ProgressBar: typeof import('./components/Job/ProgressBar.vue')['default']
    ResultViewer: typeof import('./components/Result/ResultViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmartDownloadButton: typeof import('./components/SmartDownloadButton.vue')['default']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    TrainingDashboard: typeof import('./components/TrainingDashboard.vue')['default']
    TrainingTaskManager: typeof import('./components/TrainingTaskManager.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
